train:
  max_episodes: 30000
  max_steps: 300
  save_frequency: 100
  log_dir: logs
  agent_name: SARSAAgent

QAgent:
  gamma: 0.98
  alpha: 0.05
  eps_start: 1.0
  eps_end: 0.05
  eps_decay: 0.99
  num_bins: 30

SARSAAgent:
  gamma: 0.98
  alpha: 0.05
  eps_start: 1.0
  eps_end: 0.05
  eps_decay: 0.99
  num_bins: 30

DQNAgent:
  batch_size: 512
  lr: 1.0e-4
  gamma: 0.98
  eps_start: 1.0
  eps_end: 0.05
  eps_decay: 0.99
  device: "cuda:0"

DoubleDQNAgent:
  batch_size: 512
  lr: 5.0e-4
  gamma: 0.98
  eps_start: 1.0
  eps_end: 0.05
  eps_decay: 200
  target_update: 10
  device: "cuda:0"
